Challenge completed
Akkadu/Akkadu_Challenges pull request #4
Opened 2019-10-28 07:51 UTC by deevannaveed

Challenge completed and an extra design is also included

2019-11-04 10:26 UTC, TNieminen commented
# The requirements for the challenge were as follows:

## Do not use any UI libraries if you can. We'd like to know that you understand the concepts of building components that are reusable.

 - No libraries, used flex 

## All CSS should be written in SCSS.

- Check

## Make use of components in your user interfaces as much as possible.

- You split the list element into a separate component. Thumbs up! I feel the profile should be a overlay component since now we are a bit needlessly doing additional routing. This has also led into a bug where if you delete the last element using the profile page delete button the page automatically refreshes rather than asking the user to request for more profiles.

## Your components should be tested.

- No tests. Testing is super important for reliable continuous deployment. : (

## Make use of the color palette provided below:

- Check

# Other evaluation criteria

## Asking good questions is a good quality. We will not penalize you for asking questions. In an actual work environment, we prefer that engineers spend 30 minutes talking a problem over with someone than spend an entire day building the wrong thing.

- You asked clarifying questions about the task at hand. Good!

## We're looking for signs you understand concepts such as errors, events, promises, and reactivity, and how those concepts are implemented in Javascript.

- You are using vue directives for reactivity and correctly using lifecycle hooks. You handling of the fetch error is also adequate, no obvious errors.

## We're also looking for signs that you understand good styling practices.

- SCSS variables are relative, not absolute px values, good. Otherwise clear naming and easy to read

## We like code that is clean, readable and easily testable. Your ability to demonstrate this is a big plus.

- Code is in overall easy to read and understand. Usage of templates inside templates is a bit uncommon, it does work, but using maybe div with V-show would be more natural. I would also prefer the scss to be inline rather than globally imported, now to edit one scss property in one file I need to navigate through all of the scss.

## We're looking for an understanding of accessibility and good performance metrics in your submission.

- I appreciate you chunking the profile page route with webpack magick comments!

## Please comment your code.

- Comments exist. Using JSdocs type commenting could be more informative so you could clearly define what the functions return and expect as an input. 

@codebender828  Will still look at the code. He's mainly in charge of our front-end development!

2019-11-05 16:13 UTC, codebender828 requested changes
Hey @deevannaveed ! Congratulations and great work with completing the challenge.

I've made a few comments on what you did well and what could have improved. 

Let me know if you would like to make some changes or if you feel happy with this submission! Otherwise here is an evaluation of your code:

**The requirements for the challenge were as follows:**
- [x]  All CSS should be written in SCSS.
- [x] Do not use any UI libraries if you can. We'd like to know that you understand the concepts of building components that are reusable.
- [x] Make use of components in your user interfaces as much as possible.
- [x] Your components should be tested.
- [x] Make use of the color palette provided

### Other evaluation criteria
**Asking good questions is a good quality. We will not penalize you for asking questions. In an actual work environment, we prefer that engineers spend 30 minutes talking a problem over with someone than spend an entire day building the wrong thing.**

I appreciate that you took time to ask some questions about the project before implementing it. I think communication is key when working on a team.

**We're looking for signs you understand concepts such as errors, events, promises, and reactivity, and how those concepts are implemented in Javascript.**
Good error handling. Would have been better to even show a message if something goes wrong to the user for a complete user feedback loop.

**We're also looking for signs that you understand good styling practices.**
I liked your use of SCSS variables and nested styles to keep your styles scoped and concise.

**We like code that is clean, readable and easily testable. Your ability to demonstrate this is a big plus**
Your code was overall legible. I also noticed that you didn't make use of Vue's style tags in your components. Not sure why? It would have made your scss file a lot smaller and easier to navigate. CSS files get large very quickly and you had already hit 360+ lines in a single tiny application. 😅

**We're looking for an understanding of accessibility and good performance metrics in your submission.**
- I think you did quite well with performance. I think you also could have done even better. Since this is client-side challenge, you needn't have used `isomorphic-fetch` package which also requires the `es6-promise` polyfill. This would make your app even more performant.
- I also noticed a lot of issues with accessibility. Especially to do with buttons. Leveraging HTML internals for some functions makes your work a lot easier. I shared an example with the `span` button implementation you made.

**Please comment your code.**
A better implementation of commenting is to use a convention that more people understand like JSdoc. I share a link to it in my review.  This will be useful in your future as well as a dev.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile-2/src/assets/envelope-solid.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="envelope" class="svg-inline--fa fa-envelope fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path f
I couldn't see where you were using this file. The better solution here would have been to use an icon library like font awesome or MDI.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile-2/src/components/ListItem.vue
> +        <span class="delete-btn" @click="deleteUser(user)">
Using a button is the more accessible DOM node to use here since it's an interactive element.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile-2/src/scss/_variables.scss
> +//@import url("https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap");
Clutter. You can always remove unused code so it's easier to maintain over time.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile-2/src/views/Home.vue
> +            // To fetch the users data from the endpoint.
I appreciate your comments here. I also think that it's better to use a more conventional pattern like [jsdoc](https://devdocs.io/jsdoc/) to document your functions. Internal procedures should otherwise be self documenting unless it's a unique case.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile-2/src/views/Profile.vue
> +            //this will remove the user from vuex store and route back to the home component.
Same here about JSdocs.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile-2/src/views/Profile.vue
> +            window.scrollTo(0, 0);
I also appreciate you taking user experience into account

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile-2/src/views/Profile.vue
> +            <i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp;&nbsp; Back to Profiles
Could you not have used a margin here? Not sure whether this icon space is the best use of a non-breaking space entity.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/components/ListItem.vue
> +        <span class="delete-btn" @click.stop="deleteUser(user)">
Same here about accessibility. If you would like to use a span then you'd need to give it `role` `tabindex` and `aria-label` attributes. Below is an example of a fully accessible span implementation of a button.

```vue
<span
  role="button"
  aria-label="Span Button"
  tabindex="0"
  @click.stop="deleteUser(user)"
  @keydown.space.prevent="deleteUser(user)"
>
 Span Button
</span>
```

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/components/ListItem.vue
> +            deleteUser(user) {
Same here about methods documentation with JSdoc

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/components/Profile.vue
> +                <img :src="user.photo" alt="User profile photo"/>
You could bind the user's name to the alt attribute.
```vue
<img :src="user.photo" :alt="user.name" />
```

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/components/Profile.vue
> +            deleteProfile(user) {
Same about the methods documentation

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/components/Profile.vue
> +            setSelectedUser() {
I took some time to look through this solution. I think the `users-profile-2` solution was simpler and better. Using the router parameters to handle this is the solution I was looking for.

Alternatively, you could use [dynamic components](https://vuejs.org/v2/guide/components-dynamic-async.html) in the `Home.vue` file.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/scss/_variables.scss
> +:root {
This could be removed since we're using sass variables 👍

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/scss/main.scss
> +  }
This is a great use of sass pseudo styles. I noticed a lack of `&:focus` styles as well which are fairly important.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/scss/main.scss
> +  width: 90vw;
Using `padding` would have been the better way to pad the `.home` container as opposed to hard coding the width.

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/scss/main.scss
> +    width: 86%;
Same here about using `padding` vs. `width`

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/scss/main.scss
> +  .home {
Same here about using `padding` vs. `width`

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/src/scss/main.scss
> +  .home {
Same here about using `padding` vs. `width`

2019-11-05 16:13 UTC, codebender828 commented on front-end-engineer/submission/muhammad-naveed/users-profile/tests/unit/list_item.spec.js
> +import {shallowMount} from '@vue/test-utils'
Great to see some tests for this

2020-04-02 02:58 UTC, TNieminen approved these changes

2020-04-02 02:58 UTC, closed without merging